package com.nf.ldl.dao;

import com.nf.ldl.model.Consumer;
import java.util.List;

public interface ConsumerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String conId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer
     *
     * @mbg.generated
     */
    int insert(Consumer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer
     *
     * @mbg.generated
     */
    Consumer selectByPrimaryKey(String conId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer
     *
     * @mbg.generated
     */
    List<Consumer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Consumer record);
}