package com.nf.ldl.dao;

import com.nf.ldl.model.Distribution;
import java.util.List;

public interface DistributionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribution
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer disId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribution
     *
     * @mbg.generated
     */
    int insert(Distribution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribution
     *
     * @mbg.generated
     */
    Distribution selectByPrimaryKey(Integer disId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribution
     *
     * @mbg.generated
     */
    List<Distribution> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribution
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Distribution record);
}