package com.nf.ldl.dao;

import com.nf.ldl.model.Handover;
import java.util.List;

public interface HandoverMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table handover
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String hanStartCity);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table handover
     *
     * @mbg.generated
     */
    int insert(Handover record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table handover
     *
     * @mbg.generated
     */
    Handover selectByPrimaryKey(String hanStartCity);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table handover
     *
     * @mbg.generated
     */
    List<Handover> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table handover
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Handover record);
}